Payroll preparation
Numigi/odoo-timesheet-addons pull request #8
Opened 2020-01-14 21:58 UTC by ddufresne

https://isidor.numigi.net/web#id=18949&action=292&active_id=597&model=project.task&view_type=form&menu_id=200

2020-01-14 22:00 UTC, ddufresne commented on payroll_preparation/__manifest__.py
> +{
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Statement seems to have no effect](https://app.codacy.com/manual/numigi/odoo-timesheet-addons/pullRequest?prid=4821367)

2020-01-14 22:00 UTC, ddufresne commented on payroll_preparation/__init__.py
> +from . import models
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: ['.models' imported but unused](https://app.codacy.com/manual/numigi/odoo-timesheet-addons/pullRequest?prid=4821367)

2020-01-14 22:00 UTC, ddufresne commented on payroll_preparation/models/__init__.py
> +from . import (
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: ['.payroll_preparation_line' imported but unused](https://app.codacy.com/manual/numigi/odoo-timesheet-addons/pullRequest?prid=4821367)

2020-01-15 18:49 UTC, foutoucour requested changes

2020-01-15 18:49 UTC, foutoucour commented on payroll_period/security/ir_rule.xml
> +        <field name="domain_force">['|', ('company_id', '=', False), ('company_id', 'child_of', [user.company_id.id])]</field>
Tiens, pourquoi ce changement dans un module qui semble sans connection ?

2020-01-15 18:49 UTC, foutoucour commented on payroll_preparation/README.rst
> +By preparation of payroll, we meen the gathering of relevant data to process a payslip.
```suggestion
By preparation of payroll, we mean the gathering of relevant data to process a payslip.
```

2020-01-15 18:49 UTC, foutoucour commented on payroll_preparation/models/payroll_preparation_line.py
> +    week = fields.Integer(
Que représente `week` ? Le numéro de la semaine ?

2020-01-15 18:49 UTC, foutoucour commented on payroll_preparation/models/payroll_preparation_line.py
> +                    'for the payroll entry {entry}.'
Il manque le `.format()` j'ai l'impression

2020-01-15 19:00 UTC, ddufresne commented on payroll_period/security/ir_rule.xml
> +        <field name="domain_force">['|', ('company_id', '=', False), ('company_id', 'child_of', [user.company_id.id])]</field>
@foutoucour un pattern général dans Odoo pour éviter des bugs subtils dans la création d'un enregistrement. C'est toujours comme cela que les règles multi-société s'écrivent.

J'avais découvers cette anomalie dans un autre module. Lorsque je retrouve ces règles, j'en profite pour les mettre à jour.

2020-01-15 19:01 UTC, ddufresne commented on payroll_preparation/models/payroll_preparation_line.py
> +    week = fields.Integer(
oui

2020-01-15 19:06 UTC, ddufresne commented on payroll_preparation/models/payroll_preparation_line.py
> +                    'for the payroll entry {entry}.'
corrigé

2020-01-15 19:06 UTC, ddufresne commented on payroll_preparation/models/payroll_preparation_line.py
> +    week = fields.Integer(
Je viens de renommer le champ pour week_number, ce sera plus explicite.

2020-01-15 19:17 UTC, foutoucour approved these changes

2020-01-15 19:45 UTC, merged